// AUTO-GENERATED by publish_git.py — do not edit by hand.
// Maps company slug -> SHA-256 hex of its password. Not served (outside _site).
export const PASSWORDS = {
  "demo": "8ad7d9dcb49893d10e4429c4b107bca23a1b27cc8ac27ebeabdccf8e9bd00c61"
};
